[2023-10-17T11:18:57.530+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [queued]>
[2023-10-17T11:18:57.536+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [queued]>
[2023-10-17T11:18:57.537+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T11:18:57.550+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-02-09 00:00:00+00:00
[2023-10-17T11:18:57.557+0000] {standard_task_runner.py:57} INFO - Started process 504 to run task
[2023-10-17T11:18:57.559+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-02-09T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmp2qaufafc']
[2023-10-17T11:18:57.560+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask waiting_for_data
[2023-10-17T11:18:57.597+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [running]> on host 238c1d4ff767
[2023-10-17T11:18:57.661+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-02-09T00:00:00+00:00'
[2023-10-17T11:18:57.668+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:18:57.668+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-17T11:18:57.669+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-17T11:18:57.669+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-17T11:18:57.677+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210209T000000, start_date=20231017T111857, end_date=20231017T111857
[2023-10-17T11:18:57.731+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T11:18:57.754+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T10:42:26.305+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [queued]>
[2023-10-18T10:42:26.311+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [queued]>
[2023-10-18T10:42:26.312+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T10:42:26.326+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-02-09 00:00:00+00:00
[2023-10-18T10:42:26.335+0000] {standard_task_runner.py:57} INFO - Started process 1468 to run task
[2023-10-18T10:42:26.337+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-02-09T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpedm5gimi']
[2023-10-18T10:42:26.338+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask waiting_for_data
[2023-10-18T10:42:26.388+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [running]> on host 2473b23ba069
[2023-10-18T10:42:26.466+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-02-09T00:00:00+00:00'
[2023-10-18T10:42:26.483+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T10:42:26.486+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210209T000000, start_date=20231018T104226, end_date=20231018T104226
[2023-10-18T10:42:26.497+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task waiting_for_data (The conn_id `fs_default` isn't defined; 1468)
[2023-10-18T10:42:26.510+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T10:42:26.542+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T11:16:53.495+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [queued]>
[2023-10-18T11:16:53.504+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [queued]>
[2023-10-18T11:16:53.505+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T11:16:53.518+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-02-09 00:00:00+00:00
[2023-10-18T11:16:53.526+0000] {standard_task_runner.py:57} INFO - Started process 206 to run task
[2023-10-18T11:16:53.529+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-02-09T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpf4j8avi3']
[2023-10-18T11:16:53.530+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask waiting_for_data
[2023-10-18T11:16:53.594+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [running]> on host 0e68aa52dfc7
[2023-10-18T11:16:53.716+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-02-09T00:00:00+00:00'
[2023-10-18T11:16:53.726+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-18T11:16:53.726+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-18T11:16:53.727+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-18T11:16:53.727+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-18T11:16:53.751+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210209T000000, start_date=20231018T111653, end_date=20231018T111653
[2023-10-18T11:16:53.782+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-18T11:16:53.837+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-19T12:10:05.212+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [queued]>
[2023-10-19T12:10:05.220+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [queued]>
[2023-10-19T12:10:05.221+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:10:05.231+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-02-09 00:00:00+00:00
[2023-10-19T12:10:05.237+0000] {standard_task_runner.py:57} INFO - Started process 243 to run task
[2023-10-19T12:10:05.240+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-02-09T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpaylnmofp']
[2023-10-19T12:10:05.242+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask waiting_for_data
[2023-10-19T12:10:05.283+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-02-09T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:10:05.328+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-02-09T00:00:00+00:00'
[2023-10-19T12:10:05.340+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-19T12:10:05.342+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210209T000000, start_date=20231019T121005, end_date=20231019T121005
[2023-10-19T12:10:05.348+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task waiting_for_data (The conn_id `fs_default` isn't defined; 243)
[2023-10-19T12:10:05.373+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T12:10:05.404+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
